name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTJmNDQ0NmQtZWRlOS00ZjJmLWIxYjEtNzgxNjQ5MmY2MDQ2IiwidGVuYW50X2lkIjoiM2YzMzM4OTE2YTA3MWZkNDM1ZThkMzY2ODQwYTFlYjYzMTEyYTU4MDk4ZmMxYTExNTc1NzExMmM5NTFhNjM5NiIsImludGVybmFsX3NlY3JldCI6IjE5Njc1ZGJiLWRmMGYtNDMxNS1hZmIzLWQxNTc2MTI4NmNkNSJ9.n_e85325JfmNvoRb66VjnTMg1_41RE6VqjJ09z0XUXU"
JWT_SECRET = "asdasdasd"

